spring:
  application:
    name: lecture-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
#  r2dbc:
#    url: r2dbc:h2:mem:///msa
#    username: sa
#    password:

server:
#  port: 0
  port: 8091
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.value}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
#debug: true